version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:6.10

jobs:
  install-deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install local yarn
          command: npm run yarn:install
      - run:
          name: Install dependencies using local yarn
          command: npm run yarn:install-deps
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - .eslintrc
            - node_modules
            - src
            - package.json
            - webpack.config.js

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run code checks
          command: npm run lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Build application
          command: npm run dist

  release-major:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Release major version
          command: npm run dist

  release-minor:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Release minor version
          command: npm run dist

  release-patch:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Release patch version
          command: npm run dist

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - install-deps
      - test:
          requires:
            - install-deps
      - approve-major:
         type: approval
         requires:
           - install-deps
      - approve-minor:
         type: approval
         requires:
           - install-deps
      - approve-patch:
         type: approval
         requires:
           - install-deps
      - release-major:
          requires:
            - approve-major
      - release-minor:
          requires:
            - approve-minor
      - release-patch:
          requires:
            - approve-patch
