version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:6.10

jobs:
  install-deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install local yarn
          command: npm run yarn:install
      - run:
          name: Install dependencies using local yarn
          command: npm run yarn:install-deps
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - .git
            - .eslintrc
            - node_modules
            - src
            - package.json
            - webpack.config.js

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run code checks
          command: npm run lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Build application
          command: npm run dist

  release-major:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Create and publish major release
          command:
            - npm version major
            - git push origin $CIRCLE_BRANCH
            - git push --tags

  release-minor:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Preparing git working directory
          command: |
            git clean -d -f
            git checkout -- .
            git config user.name "ci-bot"
            git config user.email "ci-bot@circleci.com"
      - run:
          name: Bump minor version
          command: npm version minor
      - run:
          name: Push created version
          command: git push origin $CIRCLE_BRANCH
      - run:
          name: Publish created version tag
          command: git push --tags

  release-patch:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Create and publish patch release
          command:
            - npm version patch
            - git push origin $CIRCLE_BRANCH
            - git push --tags

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - install-deps
      - test:
          requires:
            - install-deps
      - approve-major:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - approve-minor:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - approve-patch:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release-major:
          requires:
            - approve-major
      - release-minor:
          requires:
            - approve-minor
      - release-patch:
          requires:
            - approve-patch
