version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install local yarn
          command: npm run yarn:install

      - run:
          name: Install dependencies using local yarn
          command: npm run yarn:install-deps

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Run code checks
          command: npm run lint
