version: 2

base-params: &base-params
  working_directory: ~/app
  docker:
    - image: circleci/node:6.10

prepare-git: &prepare-git
  name: Preparing git working directory
  command: |
    git clean -d -f
    git checkout -- .
    git config user.name "ci-bot"
    git config user.email "ci-bot@circleci.com"

publish-to-git: &publish-to-git
  name: Publish created version
  command: |
    git push origin $CIRCLE_BRANCH
    git push --tags

jobs:
  install-deps:
    <<: *base-params
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install local yarn
          command: npm run yarn:install
      - run:
          name: Install dependencies using local yarn
          command: npm run yarn:install-deps
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - .git
            - .eslintrc
            - node_modules
            - src
            - package.json
            - webpack.config.js

  test:
    <<: *base-params
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run code checks
          command: npm run lint

  build:
    <<: *base-params
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Build application
          command: npm run dist

  release-major:
    <<: *base-params
    steps:
      - attach_workspace:
          at: ./
      - run:
          <<: *prepare-git
      - run:
          name: Bump major version
          command: npm version major
      - run:
          <<: *publish-to-git

  release-minor:
    <<: *base-params
    steps:
      - attach_workspace:
          at: ./
      - run:
          <<: *prepare-git
      - run:
          name: Bump minor version
          command: npm version minor
      - run:
          <<: *publish-to-git

  release-patch:
    <<: *base-params
    steps:
      - attach_workspace:
          at: ./
      - run:
          <<: *prepare-git
      - run:
          name: Bump patch version
          command: npm version patch
      - run:
          <<: *publish-to-git

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - install-deps
      - test:
          requires:
            - install-deps
      - approve-major:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - approve-minor:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - approve-patch:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release-major:
          requires:
            - approve-major
      - release-minor:
          requires:
            - approve-minor
      - release-patch:
          requires:
            - approve-patch
